### PR TITLE
Filtering out solution folders

### PR DESCRIPTION
**Pull request by wwwlicious**
Currently solution folders generate an error message when executing `StyleCopAnalyse`. This PR filters them out

### CODE REVIEW

**Comment by Symbianx** [comment]
This issue should already be resolved with PR #3, which has been siting there for almost 2 months. Unfortunately it looks to me that the owner has abandoned the project.

**Comment by wwwlicious** [comment]
Thanks, I saw that after submitting the PR. The nuget package is part of the cake-contrib group so it should  be possible for a fork of the project to build and update the package on nuget.org.

Currently we're just running our own (higher) version of this package from an internal  nuget server. Pity.

**Comment by gep13** [comment]
> @wwwlicious said...
> he nuget package is part of the cake-contrib group so it should be possible for a fork of the project to build and update the package on nuget.org.

I would prefer if we didn't have to fork the repo, but rather, if it is determined that this repo is no longer maintained, get it moved into the Cake-Contrib organisation.  Let me try reaching out to @Ashthos directly.

**Comment by wwwlicious** [comment]
Thanks @gep13 :+1:

**Comment by Ashthos** [comment]
Apologies chaps, I don't get emails from github into an account I check often. Reviewed and merged other PR.

**Comment by gep13** [comment]
@wwwlicious are you in a position to take the new NuGet package that @Ashthos has created for a spin?

**Comment by wwwlicious** [comment]
@gep13 will do tomorrow morning 👍

**Comment by wwwlicious** [comment]
All looks ok with v1.1.1. Closing

**Pull request closed without merging**
